global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
